# Should work under travis and appveyor.
# https://github.com/joyent/node-ldapjs
# https://github.com/mozilla-services/mozilla-idp/blob/master/server/lib/ldapMock.js
# you asked...

language: csharp
mono: none
dotnet: 2.1.300
sudo: false
os:
  - linux
  - osx

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=1

script:
  - cd Linq2Ldap.Core.Tests
  - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutputFormat=opencover /p:CoverletOutput=./ Linq2Ldap.Core.Tests.csproj


#addons:
#  apt:
#    packages:
#      - ldap-utils

# before_script:
#  - mkdir /tmp/slapd
#  - slapd -f LDAPData.IntegrationTest/slapd.conf -h ldap://localhost:3389 &
#  - sleep 3
#  - ldapadd -h localhost:3389 -D cn=admin,dc=example,dc=com -w test -f LDAPData.IntegrationTest/ldif_data/base.ldif
#  - ldapadd -h localhost:3389 -D cn=admin,dc=example,dc=com -w test -f LDAPData.IntegrationTest/ldif_data/INITIAL_TESTDATA.ldif